name: 'Terraform'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['dev', 'staging', 'prod']
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Set Google Credentials
      id: credentials
      run: |
        if [ "${{ matrix.environment }}" = "dev" ]
        then
          echo "::set-output name=creds::${{ secrets.DEV_GOOGLE_CREDENTIALS }}"
        elif [ "${{ matrix.environment }}" = "staging" ]
        then
          echo "::set-output name=creds::${{ secrets.STAGING_GOOGLE_CREDENTIALS }}"
        else
          echo "::set-output name=creds::${{ secrets.PROD_GOOGLE_CREDENTIALS }}"
        fi

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ steps.credentials.outputs.creds }}

    - name: Terraform Workspace Select
      run: terraform workspace select ${{ matrix.environment }}

    - name: Terraform Plan
      run: terraform plan -var-file=${{ matrix.environment }}.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ steps.credentials.outputs.creds }}

    - name: Terraform Apply (Development)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && matrix.environment == 'dev'
      run: terraform apply -auto-approve -var-file=${{ matrix.environment }}.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ steps.credentials.outputs.creds }}
        
    - name: Terraform Apply (Staging)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && matrix.environment == 'staging'
      run: terraform apply -auto-approve -var-file=${{ matrix.environment }}.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ steps.credentials.outputs.creds }}
        
    - name: Terraform Apply (Production)
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && matrix.environment == 'prod'
      run: terraform apply -auto-approve -var-file=${{ matrix.environment }}.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ steps.credentials.outputs.creds }}
