name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:  
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Configure gcloud 
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > sa_key.json
        gcloud auth activate-service-account --key-file=sa_key.json
    
    - name: Terraform Init 
      run: terraform init
    
    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'  
      run: terraform apply -auto-approve
